### ISSUE TITLE
To do: add gulp-svgmin

### ISSUE THREAD

**Issue by ttomdewit** [ttomdewit/hulk#1]
https://github.com/ben-eb/gulp-svgmin

**Comment by ttomdewit** [comment]
Alternatively, check out https://www.npmjs.com/package/gulp-iconify

**Comment by lukewhitehouse** [comment]
You may find this annoying :P https://github.com/gavro/gulp-iconify/issues/9

**Comment by ttomdewit** [comment]
@lukewhitehouse I read that they've fixed the issue. I'm reading up on SVG icon workflow (https://github.com/lukewhitehouse/SVG-icon-workflow) to see if I can use that.

Thanks for sharing.

**Comment by ttomdewit** [comment]
Currently using Gulp-iconify. Seems to be working with nice fallbacks.

**Comment by ttomdewit** [comment]
Close issue: https://github.com/ttomdewit/hulk/commit/bfa971775486510b1677794e0b145127befe728b

**Comment by ttomdewit** [comment]
Re-evaluate SVG solution. Possibly look at other solutions.

**Comment by ttomdewit** [comment]
Current solutions works with both `gulp-svg-symbols` and `gulp-svg2png`. Not using the PNG fallback at this time till I figure out a way to determine if the guest's browser can't work with SVG and needs the PNG fallback.
